site_name: Capsule
site_url: https://bots-garden.github.io/capsule/
site_author: Philippe CharriÃ¨re (@k33g)
site_description: >-
  **Capsule** is a **WebAssembly Function Runner**.
# Repository
repo_name: bots-garden/capsule
repo_url: https://github.com/bots-garden/capsule

# Copyright
copyright: Copyright &copy; 2022 - 2023 Philippe CharriÃ¨re


nav:
    - ğŸ  Home: index.md
    - ğŸ’Š Install Capsule: install.md
    - ğŸš€ Getting Started:
      - Install the Cabu CLI: getting-started-cabu-inst.md
      - Generate a function: getting-started-cabu-gen.md
      - Build the function module: getting-started-cabu-build.md
      - Serve the function module: getting-started-cabu-serve.md
      - Serve the module frome an url: getting-started-cabu-serve-url.md
      - Reload the module: getting-started-cabu-reload.md
    - ğŸ“ Developer guide:
      - First CLI function: first-cli-function.md
      - First HTTP function: first-http-function.md
      - First Nats function: first-nats-function.md
      - First MQTT function: first-mqtt-function.md
    - ğŸ› ï¸ Host functions:
      - Introduction: host-functions-intro.md
      - Log: host-functions-log.md
      - Files: host-functions-files.md
      - Environment: host-functions-env.md
      - HTTP Requests: host-functions-http.md
      - Memory cache: host-functions-memory.md
      - Redis: host-functions-redis.md
      - CouchBase: host-functions-couchbase.md
      - Nats: host-functions-nats.md
      - MQTT: host-functions-mqtt.md
      - Errors: host-functions-errors.md
    - ğŸ¥˜ CookBook: cookbook.md
    - ğŸ“™ Refs: references.md
    - ğŸ§ª Capsule FaaS: capsule-faas.md

theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      auto_title: false
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences




#theme:
#    name: readthedocs
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - rust
#        - golang
#        - bash
#        - javascript
